language: android

branches:
  only:
    - feature/travis

android:
  components:
    - platform-tools
    - tools
    - build-tools-20.0.0
    - android-19
    - android-18
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
