language: android
branches:
  only:
    - feature/travis

before_install:
    - echo "y" | android update sdk --no-ui --filter platform-tools,tools
    - echo "y" | android update sdk --no-ui --filter build-tools-20.0.0
    - echo "y" | android update sdk --no-ui --filter android-19
    - echo "y" | android update sdk --no-ui --filter addon-google_apis-google-18,extra-android-m2repository,extra-google-m2repository

install:
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
