language: android

branches:
  only:
    - feature/travis

android:
  components:
    - build-tools-20.0.0
    - android-19
    - android-18
    - extra

after_failure: "cat home/travis/build/lalbuquerque/notes/app/build/reports/tests/debug/index.html"
